/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "surface-bright": "#393939",
        "tertiary-fixed": "#ffe08d",
        "on-error-container": "#ffdad6",
        "error-container": "#93000a",
        "on-surface-variant": "#b9cbb9",
        "on-surface": "#e2e2e2",
        "on-primary-container": "#007139",
        "on-primary": "#003919",
        "on-secondary-container": "#94f0ab",
        "on-error": "#690005",
        "outline": "#849585",
        "inverse-primary": "#006d37",
        "primary-container": "#00ff88",
        "on-tertiary-fixed": "#241a00",
        "surface-container-highest": "#353535",
        "on-primary-fixed": "#00210c",
        "tertiary": "#fffaf7",
        "background": "#131313",
        "inverse-surface": "#e2e2e2",
        "outline-variant": "#3b4b3d",
        "on-background": "#e2e2e2",
        "error": "#ffb4ab",
        "primary-fixed": "#60ff99",
        "surface-tint": "#00e479",
        "on-tertiary-container": "#795f01",
        "surface-container-low": "#1b1b1b",
        "surface-dim": "#131313",
        "secondary-fixed-dim": "#7eda96",
        "on-tertiary-fixed-variant": "#584400",
        "secondary-fixed": "#9af7b0",
        "surface-variant": "#353535",
        "inverse-on-surface": "#303030",
        "on-primary-fixed-variant": "#005228",
        "surface-container": "#1f1f1f",
        "surface-container-lowest": "#0e0e0e",
        "primary": "#f1ffef",
        "secondary-container": "#027038",
        "tertiary-fixed-dim": "#e5c364",
        "on-secondary-fixed-variant": "#005228",
        "primary-fixed-dim": "#00e479",
        "surface-container-high": "#2a2a2a",
        "on-secondary": "#003919",
        "on-secondary-fixed": "#00210c",
        "surface": "#131313",
        "secondary": "#7eda96",
        "on-tertiary": "#3d2f00",
        "tertiary-container": "#ffdb79",
        neon: '#00ff88'
      },
      borderRadius: {
        "DEFAULT": "0px",
        "lg": "0px",
        "xl": "0px",
        "full": "0px"
      },
      fontFamily: {
        headline: ["Space Grotesk", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Space Grotesk", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
        sans: ["Inter", "system-ui", "sans-serif"]
      },
      animation: {
        'fade-in': 'fadeIn 0.3s ease-in',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: 0, transform: 'translateY(8px)' },
          '100%': { opacity: 1, transform: 'translateY(0)' },
        },
      },
    },
  },
  plugins: [],
};
