apiVersion: v1
kind: Secret
metadata:
  name: obelisk-secrets
  namespace: obelisk
type: Opaque
stringData:
  SECRET_KEY: "CHANGE_ME_SECRET_KEY_64PLUS_CHARS"
  AUTH_PASSWORD: "CHANGE_ME_AUTH_PASSWORD"
  POSTGRES_PASSWORD: "CHANGE_ME_POSTGRES_PASSWORD"
  NEO4J_PASSWORD: "CHANGE_ME_NEO4J_PASSWORD"
  NEO4J_AUTH: "neo4j/CHANGE_ME_NEO4J_PASSWORD"
